name: HGLaborDuels
author: BestAuto
version: 1.0.0

main: de.hglabor.plugins.duels.Manager
api-version: 1.16

depend:
  - AsyncWorldEdit
commands:
  arena:
  challenge:
    aliases:
      - c
      - duel
  setspawn:
  spec:
  stats:
  dueloverview:
  hub:
    aliases:
      - lobby
      - l
  leave:
    aliases:
      - giveup
      - surrender
  follow:
  staffmode:
    aliases:
      - v
      - vanish
      - staff
      - mod
      - modmode
  party:
  spawn:
  tournament: